import type { DirectoryMedia } from './types';

/**
 * Hotel photos and listing details for directory batch 1.
 * Photos come from each property's own website or its own OTA listing;
 * details are included only where those sources state them.
 */
export const directoryMedia1: Record<string, DirectoryMedia> = {
  'hptdc-hotel-bhagsu-mcleod-ganj': {
    images: [
      { url: 'https://hptdc.hp.gov.in/public/uploads/hotel_images/1765786642_693fc4123496d_Hotel%20Bhagsu%20Mcleodganj.jpg', alt: 'Main building and garden pathway at HPTDC Hotel Bhagsu, McLeod Ganj', category: 'exterior' },
      { url: 'https://hptdc.hp.gov.in/public/uploads/hotel_images/1765786642_693fc412354e4_Huts.jpg', alt: 'Lawns, deodar trees and garden huts at HPTDC Hotel Bhagsu, McLeod Ganj', category: 'exterior' },
      { url: 'https://hptdc.hp.gov.in/public/uploads/hotel_images/1765786658_693fc422b6a53_Deluxe%20room.jpg', alt: 'Deluxe room with wooden floor at HPTDC Hotel Bhagsu, McLeod Ganj', category: 'room' },
      { url: 'https://hptdc.hp.gov.in/public/uploads/hotel_images/1765786658_693fc422b8015_Suite%20room.jpg', alt: 'Suite room with sitting area and TV at HPTDC Hotel Bhagsu, McLeod Ganj', category: 'room' },
    ],
    photo_source: 'https://hptdc.hp.gov.in/hotel-detail/25',
    room_types: [
      { name: 'Deluxe Room', description: 'Deluxe category room in the main hotel building.' },
      { name: 'Suite', description: 'Larger suite room with a sitting area.' },
      { name: 'Hut', description: 'Separate cottage-style hut set on the lawns within the hotel grounds.' },
    ],
    amenities: ['Restaurant', 'Bar', 'Parking', 'Room service', 'WiFi', 'Laundry service', 'LED TV', 'Satellite TV', 'Intercom', 'Taxi on demand', 'Card payments accepted'],
  },
  'green-hotel-bhagsu-road-mcleod-ganj': {
    images: [
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/61501863.jpg?k=bdda5c528bc89dc1e33e38c7aa37a8b18c6840aff85d91f02db2b55c64f82cce', alt: 'Building with balcony corridors and garden at Green Hotel, Bhagsu Road, McLeod Ganj', category: 'exterior' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/492876864.jpg?k=dea0ca1bb204f20f8293de2777c4e605da7f376e749f70926e4511ac51a51a3c', alt: 'Double room with balcony door at Green Hotel, McLeod Ganj', category: 'room' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/60401421.jpg?k=de871504dcedf60760aedf5f1dc33591458fab2801f795b404b0a6a37fe89e0c', alt: 'Double room with chairs by the window at Green Hotel, McLeod Ganj', category: 'room' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/60401428.jpg?k=d93d6be2cccb8e95d83d9be77a42320c7cc301526cfa2377ca6d0b50004914a2', alt: 'Double bedroom with large window at Green Hotel, McLeod Ganj', category: 'room' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/60401439.jpg?k=b2c16417bf977f46a739598a5fd5b90ae1543bdf07f81e695be47a4415befa23', alt: 'Double room with orange feature wall at Green Hotel, McLeod Ganj', category: 'room' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/61389709.jpg?k=77ccdcd627a0e7b2295501f26897fe99cda92204cad46a9cb53423ae6b9993cd', alt: 'Room with double bed and sitting area at Green Hotel, McLeod Ganj', category: 'room' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/60401319.jpg?k=f8097570ee9e63d1def5beeabb59f318eac1f656aabee61d78cb410e90c24795', alt: 'Twin-bed room at Green Hotel, McLeod Ganj', category: 'room' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/60401438.jpg?k=3d4c095804cf489cfeb71eaf1e687ab567ca1d1802b35b2297e42992edd0dcd1', alt: 'Attached bathroom with water heater at Green Hotel, McLeod Ganj', category: 'bathroom' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/60401425.jpg?k=f05044abaf959d1d07a465871a98ab8d33a1d045cd18bd953f33a402e29ecad6', alt: 'View over McLeod Ganj and the forested hills from Green Hotel', category: 'view' },
      { url: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/60401434.jpg?k=3cd885f66448664951073c5f37e0d1af1903db526998c38b2e4228c9d8b6f446', alt: 'Valley view from Green Hotel, McLeod Ganj', category: 'view' },
    ],
    photo_source: 'https://www.booking.com/hotel/in/green-dharamshala.html',
    check_in_time: '13:30',
    check_out_time: '12:00',
    amenities: ['WiFi', 'Airport shuttle', 'Balcony', 'Mountain view'],
    pet_policy: 'Pets are not allowed.',
  },
  'hotel-tibet-mcleod-ganj': {
    images: [
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6341-e1671981697593.jpg', alt: 'Hotel Tibet Bakery shopfront at Hotel Tibet, McLeod Ganj', category: 'exterior' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6616.jpg', alt: 'Entrance to the bar and restaurant at Hotel Tibet, McLeod Ganj', category: 'exterior' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6596.jpg', alt: 'Room with double bed and sitting area at Hotel Tibet, McLeod Ganj', category: 'room' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6498.jpg', alt: 'Twin room with Tibetan bedspreads at Hotel Tibet, McLeod Ganj', category: 'room' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6517.jpg', alt: 'Room with balcony door at Hotel Tibet, McLeod Ganj', category: 'room' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6573.jpg', alt: 'Twin room with window view at Hotel Tibet, McLeod Ganj', category: 'room' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6530.jpg', alt: 'Attached bathroom at Hotel Tibet, McLeod Ganj', category: 'bathroom' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6581.jpg', alt: 'Balcony view towards the hills from Hotel Tibet, McLeod Ganj', category: 'view' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6284.jpg', alt: 'Restaurant dining hall at Hotel Tibet, McLeod Ganj', category: 'restaurant' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6329.jpg', alt: 'Bar and lounge seating at Hotel Tibet, McLeod Ganj', category: 'restaurant' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6618.jpg', alt: 'Reception lobby seating at Hotel Tibet, McLeod Ganj', category: 'lobby' },
      { url: 'https://www.nyamdel.com/wp-content/uploads/2022/12/IMG_6473.jpg', alt: 'Banquet hall at Hotel Tibet, McLeod Ganj', category: 'amenity' },
    ],
    photo_source: 'https://www.nyamdel.com/shop-now/hotels/hotel-tibet-dharamshala/',
    check_out_time: '12:00',
    room_types: [
      { name: 'Standard Double', description: 'Entry-level double room with attached bathroom.' },
      { name: 'Semi-Deluxe Double', description: 'Mid-category double room with attached bathroom.' },
      { name: 'Deluxe Double', description: 'Top-category double room with attached bathroom.' },
    ],
    amenities: ['Restaurant', 'Rooftop restaurant', 'Bar', 'Bakery', 'Cable TV', 'Telephone', 'Hot water', 'Banquet hall', 'Board room'],
  },
  'backpackers-inn-jogiwara-road-mcleod-ganj': {
    images: [
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/qerihdc3qggdxpoj2gix.jpg', alt: 'Terrace and building front at Backpackers Inn, Jogiwara Road, McLeod Ganj', category: 'exterior' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/xnlpqsw0x2vmsl7bwnw2.jpg', alt: 'Private double room with mountain-view windows at Backpackers Inn, McLeod Ganj', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/tfpnfsm5hjtdbwm3e72r.jpg', alt: 'Private room with valley-view window at Backpackers Inn, McLeod Ganj', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/urh5ifjh6yuj0cbfgbsc.jpg', alt: 'Attached bathroom with water heater at Backpackers Inn, McLeod Ganj', category: 'bathroom' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/wfijicgu7xofqksf1nyt.jpg', alt: 'Painted cafe and lounge at Backpackers Inn, McLeod Ganj', category: 'restaurant' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/nnn4iekm0ac5rlmt949a.jpg', alt: 'Mural-painted dining room at Backpackers Inn, McLeod Ganj', category: 'restaurant' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/bhl2ayjqljrly3ywe2w8.jpg', alt: 'Rooftop cafe seating with mountain view at Backpackers Inn, McLeod Ganj', category: 'restaurant' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/bxe9kxrd3uby9i3grnne.jpg', alt: 'Rooftop terrace with plants and signboard at Backpackers Inn, McLeod Ganj', category: 'amenity' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/x96vriblwnmish6uz3l2.jpg', alt: 'Terrace view over the McLeod Ganj hillside from Backpackers Inn', category: 'view' },
      { url: 'https://a.hwstatic.com/image/upload/q_auto,w_1200,c_limit/propertyimages/1/101756/aa1yobutwezdvtltomxm.jpg', alt: 'Sunset over the hills from the rooftop at Backpackers Inn, McLeod Ganj', category: 'view' },
    ],
    photo_source: 'https://www.hostelworld.com/hostels/p/101756/backpackers-inn-mcleodganj/',
    check_in_time: '12:00',
    amenities: ['WiFi', 'Luggage storage', '24-hour reception', 'Travel desk', 'Currency exchange', 'Shuttle bus', 'Rooftop cafe'],
  },
  'the-belvedere-himalayan-retreat-mcleod-ganj': {
    images: [
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/DJI_0874-2.jpg', alt: 'The Belvedere Himalayan Retreat building among deodar forest, McLeod Ganj', category: 'exterior' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/Facade_1_q11d7k.jpg', alt: 'Facade and forecourt of The Belvedere Himalayan Retreat, McLeod Ganj', category: 'exterior' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/Superior_room_at_belvedere_witha_view_ikt4px.jpg', alt: 'Superior Room with balcony at The Belvedere Himalayan Retreat, McLeod Ganj', category: 'room' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/Suite_13_fawaey.jpg', alt: 'Suite bedroom with balcony and mountain view at The Belvedere Himalayan Retreat, McLeod Ganj', category: 'room' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/seating_space_inside_the_suite_t6osx6.jpg', alt: 'Seating area inside a suite at The Belvedere Himalayan Retreat, McLeod Ganj', category: 'room' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/Family_Room_6_olmtwn.jpg', alt: 'Family Room with minibar and work desk at The Belvedere Himalayan Retreat, McLeod Ganj', category: 'room' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/Suite_23_zvveod.jpg', alt: 'Suite balcony overlooking the Dhauladhar range at The Belvedere Himalayan Retreat, McLeod Ganj', category: 'view' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/IMG_4334-HDR.jpg', alt: 'Multi-cuisine restaurant at The Belvedere Himalayan Retreat, McLeod Ganj', category: 'restaurant' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/the-belvedere-himalayan-retreat-mcleodganj/dining_at_the_belvedere.jpg', alt: 'Buffet counter in the restaurant at The Belvedere Himalayan Retreat, McLeod Ganj', category: 'restaurant' },
    ],
    photo_source: 'https://www.leisurehotels.co.in/mcleodganj/belvedere-himalayan-retreat/',
    check_in_time: '13:00',
    check_out_time: '11:00',
    room_types: [
      { name: 'Deluxe Room (No View)', description: '300 sq ft room without a view.' },
      { name: 'Superior Room with Balcony', description: '300 sq ft room with a balcony facing the Dhauladhar mountains.' },
      { name: 'Family Room (No View)', description: 'Larger 480 sq ft room, without a view.' },
      { name: 'Suite with Balcony', description: '752 sq ft suite with balcony and mountain views.', max_occupancy: 3 },
    ],
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Minibar', 'Tea/coffee maker', 'In-room safe', '55-inch TV', 'Temperature control', 'Balcony', 'Mountain view', 'Conference facilities'],
  },
  'welcomheritage-natraj-mcleod-ganj': {
    images: [
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2F4b811462e87b4eb09c63ab318d45124f20251217131905663.jpg&w=1920&q=75', alt: 'Exterior of WelcomHeritage Natraj at dusk, McLeod Ganj', category: 'exterior' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2F6c6c0885-0c55-4f76-a11a-9d89d41e5c3720251217162750815.jpg&w=1920&q=75', alt: 'Standard Room with queen bed at WelcomHeritage Natraj, McLeod Ganj', category: 'room' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2Froom_0b16a91f-9d3c-44a6-a954-a8b4edbe195120260519111857725.jpeg&w=1920&q=75', alt: 'Luxury Room with balcony door at WelcomHeritage Natraj, McLeod Ganj', category: 'room' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2F5d033cc1-3144-46f3-a0f3-da62df07df0a20251217130806548.jpg&w=1920&q=75', alt: 'Premium Room with valley-view windows at WelcomHeritage Natraj, McLeod Ganj', category: 'room' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2Froom_00db18f7-adce-4648-85ce-2729c0856b1520260519111452382.jpeg&w=1920&q=75', alt: 'Luxury Suite bedroom at WelcomHeritage Natraj, McLeod Ganj', category: 'room' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2F03b69715-05eb-4b68-ad00-9dd7ffe2758420251217130931771.jpg&w=1920&q=75', alt: 'Premium Suite bedroom at WelcomHeritage Natraj, McLeod Ganj', category: 'room' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2F2e0cabe375b943b19f68e4f81dde15ae20251217131832764.jpg&w=1920&q=75', alt: 'Suite living area at WelcomHeritage Natraj, McLeod Ganj', category: 'room' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2F95fdba2ec8b04e2f8adf4cf4a9015fb020251217131832632.jpg&w=1920&q=75', alt: 'Suite lounge opening onto a valley-view balcony at WelcomHeritage Natraj, McLeod Ganj', category: 'view' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2F84dc3710a362459b99efb05e758136c720251217131832723.jpg&w=1920&q=75', alt: 'Bathroom with bathtub at WelcomHeritage Natraj, McLeod Ganj', category: 'bathroom' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2Ff93ad4a160e748cba20a9472a669606d20260129162721598.jpg&w=1920&q=75', alt: 'Bar and lounge under a timber roof at WelcomHeritage Natraj, McLeod Ganj', category: 'restaurant' },
      { url: 'https://www.welcomheritagehotels.in/_next/image?url=https%3A%2F%2Fwhcms.cinuniverse.com%2Fimages%2Fwhimages%2F5a79bf23f8654d82b577168ad125f8be20251217132047093.jpg&w=1920&q=75', alt: 'Open terrace dining with valley views at WelcomHeritage Natraj, McLeod Ganj', category: 'restaurant' },
    ],
    photo_source: 'https://www.welcomheritagehotels.in/welcomheritage-natraj/mcleodganj-hotels',
    check_in_time: '14:00',
    check_out_time: '12:00',
    room_types: [
      { name: 'Standard Room', description: 'Cosy room with a queen-size bed.', bed_type: 'Queen' },
      { name: 'Luxury Room', description: '230 sq ft (21 sq m) room.' },
      { name: 'Premium Room', description: 'Room with an expansive private balcony and valley views.' },
      { name: 'Luxury Suite', description: 'Suite with a separate living area and private balcony.' },
      { name: 'Premium Suite', description: 'Largest category at 426 sq ft (40 sq m).' },
    ],
    amenities: ['Swimming pool', 'Restaurant', 'Bar', 'Conference room', 'Free parking', 'WiFi', 'Balcony', 'Mountain view'],
  },
  'norling-house-norbulingka-sidhbari': {
    images: [
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/c5e79e54.jpg', alt: 'Stone pathway to Norling House in the Norbulingka gardens, Sidhpur', category: 'exterior' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/c5f06f23.jpg', alt: 'Painted Tibetan-style entrance of Norling House, Norbulingka Institute', category: 'exterior' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/66122233.jpg', alt: 'Stone building with balcony and outdoor seating at Norling House, Norbulingka', category: 'exterior' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/7daa1b04.jpg', alt: 'Guest room with hand-painted Tibetan furniture at Norling House, Norbulingka', category: 'room' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/230f536d.jpg', alt: 'Guest room with Tibetan painting and wooden furniture at Norling House, Norbulingka', category: 'room' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/8c1576b2.jpg', alt: 'Snow-leopard themed guest room at Norling House, Norbulingka', category: 'room' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/6f1e3eed.jpg', alt: 'Single-bed room with painted wardrobe at Norling House, Norbulingka', category: 'room' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/3c07cac1.jpg', alt: 'Suite living room with Tibetan furniture at Norling House, Norbulingka', category: 'room' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/57a3a054.jpg', alt: 'Sitting room with bookshelves at Norling House, Norbulingka', category: 'room' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/24373e14.jpg', alt: 'Private patio with seating outside a room at Norling House, Norbulingka', category: 'amenity' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/65ba08d1.jpg', alt: 'Skylit lobby at Norling House, Norbulingka Institute', category: 'lobby' },
      { url: 'https://images.trvl-media.com/lodging/105000000/104890000/104887700/104887654/bba95217.jpg', alt: 'Norling House seen from the gardens of the Norbulingka Institute', category: 'exterior' },
    ],
    photo_source: 'https://www.expedia.com/Dharamshala-Hotels-Norling-House.h104887654.Hotel-Information',
    check_in_time: '12:00',
    check_out_time: '11:30',
    amenities: ['WiFi', 'Breakfast included', 'Restaurant', 'Cafe', 'Free parking', 'Air conditioning', '24-hour front desk', 'Housekeeping', 'Hair dryer'],
  },
  'radisson-blu-resort-dharamshala-kandi': {
    images: [
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/view-from-property/16256-124822-f74910617_XL.jpg', alt: 'Aerial view of Radisson Blu Resort Dharamshala with its pool and the Dhauladhar range', category: 'exterior' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/exterior/16256-124822-f86622208_XL.jpg', alt: 'Resort buildings and driveway at Radisson Blu Resort Dharamshala', category: 'exterior' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/guest-room/16256-124822-f88034525_XL.jpg', alt: 'King guest room at Radisson Blu Resort Dharamshala', category: 'room' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/guest-room/16256-124822-f88906023_XL.jpg', alt: 'Guest room with king bed at Radisson Blu Resort Dharamshala', category: 'room' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/guest-room/16256-124822-f88034527_XL.jpg', alt: 'Guest room with king bed and wardrobe at Radisson Blu Resort Dharamshala', category: 'room' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/suite/16256-124822-f74910551_XL.jpg', alt: 'Suite bedroom with balcony at Radisson Blu Resort Dharamshala', category: 'room' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/suite/16256-124822-f88034573_XL.jpg', alt: 'Suite bedroom with sofa at Radisson Blu Resort Dharamshala', category: 'room' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/suite/16256-124822-f74910553_XL.jpg', alt: 'Suite living room with balcony at Radisson Blu Resort Dharamshala', category: 'room' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/guest-room-bath/16256-124822-f88906033_XL.jpg', alt: 'Guest bathroom with walk-in shower at Radisson Blu Resort Dharamshala', category: 'bathroom' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/restaurant/16256-124822-f81347665_XL.jpg', alt: 'All-day restaurant at Radisson Blu Resort Dharamshala', category: 'restaurant' },
      { url: 'https://media.radissonhotels.net/image/radisson-blu-resort-dharamshala/spa/16256-124822-f74910517_XL.jpg', alt: 'Spa treatment room at Radisson Blu Resort Dharamshala', category: 'amenity' },
    ],
    photo_source: 'https://www.radissonhotels.com/en-us/hotels/radisson-blu-resort-dharamshala',
    check_in_time: '14:00',
    check_out_time: '12:00',
    room_types: [
      { name: 'Standard Room', description: '32 sq m room; sleeps 2 adults plus 2 children.', bed_type: 'King', max_occupancy: 2 },
      { name: 'Standard Room - Valley View', description: '32 sq m room with valley view; sleeps 2 adults plus 2 children.', bed_type: 'King', max_occupancy: 2 },
      { name: 'Superior Room with Balcony', description: '32 sq m room with a balcony; sleeps 2 adults plus 2 children.', bed_type: 'King', max_occupancy: 2 },
      { name: 'Deluxe Room', description: '34 sq m room.', bed_type: 'King', max_occupancy: 3 },
      { name: 'Deluxe Room with Balcony and Club Access', description: '36 sq m room with balcony and club lounge access.', bed_type: 'King or 2 twin', max_occupancy: 3 },
      { name: 'Junior Suite with Club Access', description: '64 sq m suite with club lounge access.', bed_type: 'King', max_occupancy: 3 },
      { name: 'One Bedroom Suite with Club Access', description: '74 sq m suite with club lounge access.', bed_type: 'King', max_occupancy: 3 },
      { name: 'Family Duplex Room', description: '72 sq m duplex room for families.', bed_type: 'King or 2 twin', max_occupancy: 4 },
    ],
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Spa', 'Luggage storage', 'Mountain view'],
    smoking_policy: 'Smoke-free hotel.',
  },
  'atman-dharamshala-kandi': {
    images: [
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/DSC00792_poke3c.jpg', alt: 'Stone-and-timber building and lawns at Atman, Dharamshala', category: 'exterior' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/DSC00844_gzjgyi.jpg', alt: 'Atman, Dharamshala lit up at night', category: 'exterior' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/DSC00780_ydhtsb.jpg', alt: 'Swimming pool with mountain backdrop at Atman, Dharamshala', category: 'pool' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/DELUXE_ROOM_nbtfha.jpg', alt: 'Deluxe Room with carved headboard at Atman, Dharamshala', category: 'room' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/Copy_of_TGP07646-HDR-1_uk0wpq.jpg', alt: 'Room with balcony and valley view at Atman, Dharamshala', category: 'room' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/TGP07439-HDR-1_copy_t2wwaf.jpg', alt: 'Suite with swing seat and valley-view windows at Atman, Dharamshala', category: 'room' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/TGP07657_y4w6jl.jpg', alt: 'Room with carved headboard and balcony at Atman, Dharamshala', category: 'room' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/FUZION_CAFE1_ozc2oy.jpg', alt: 'Fuzion Lounge and Deck terrace at sunset, Atman, Dharamshala', category: 'restaurant' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/FUZION_LOUNGE_2_jepphp.jpg', alt: 'Fuzion lounge seating at Atman, Dharamshala', category: 'restaurant' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/DSC00760_sgnqwn.jpg', alt: 'Lounge with Tibetan-style furniture at Atman, Dharamshala', category: 'lobby' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/DSC00810_tb57vq.jpg', alt: 'Garden dining set-up at Atman, Dharamshala', category: 'amenity' },
      { url: 'https://assets.simplotel.com/simplotel/image/upload/q_80,w_1600,c_limit/atman-dharamshala/DSC00693_dcj7iq.jpg', alt: 'Buddha statue in the garden at Atman, Dharamshala', category: 'amenity' },
    ],
    photo_source: 'https://www.leisurehotels.co.in/dharamshala/atman/',
    check_in_time: '13:00',
    check_out_time: '11:00',
    room_types: [
      { name: 'Deluxe Room', description: 'Base category; 4 rooms with views of the valley.' },
      { name: 'Superior Room', description: 'Upgraded category; 7 rooms in total.' },
      { name: 'Suite', description: '350 sq ft suite.' },
      { name: 'Premium Suite', description: '375 sq ft suite with walk-in closet and a balcony facing the Dhauladhar range.' },
    ],
    amenities: ['Swimming pool', 'Restaurant', 'Bar', '24-hour front desk', '24-hour in-room dining', 'Daily housekeeping', 'Library', 'Recreation room', 'Mountain view', 'Balcony'],
  },
  'hptdc-hotel-kunal-dharamshala': {
    images: [
      { url: 'https://hptdc.hp.gov.in/public/uploads/hotel_images/1765778733_693fa52da4be0_hotel.jpg', alt: 'Building and forecourt of HPTDC Hotel Kunal, Dharamshala', category: 'exterior' },
      { url: 'https://hptdc.hp.gov.in/public/uploads/hotel_images/1765778733_693fa52da5a89_Deluxe.jpg', alt: 'Deluxe room at HPTDC Hotel Kunal, Dharamshala', category: 'room' },
      { url: 'https://hptdc.hp.gov.in/public/uploads/hotel_images/1765778733_693fa52da6504_Semi%20Deluxe.jpg', alt: 'Semi-deluxe room at HPTDC Hotel Kunal, Dharamshala', category: 'room' },
    ],
    photo_source: 'https://hptdc.hp.gov.in/hotel-detail/55',
    room_types: [
      { name: 'Deluxe Room', description: 'Airy, well-furnished room with attached bathroom.' },
      { name: 'Semi-Deluxe Room', description: 'Room with attached bathroom and hot and cold running water.' },
    ],
    amenities: ['Restaurant', 'Room service', 'Parking', 'WiFi', 'Hot water'],
  },
};
