import type { DirectoryMedia } from './types';

export const directoryMedia3: Record<string, DirectoryMedia> = {
  'regenta-inn-luxinna-heights-bhagsu': {
    images: [
      { url: 'https://pix8.agoda.net/hotelImages/42105358/-1/3cfdbe54dd918c6c0494b64ac8cc81cd.jpg?va=1&ce=0&s=1024x768', alt: 'Regenta Inn Luxinna Heights building with Regenta Inn signage, Bhagsunag', category: 'exterior' },
      { url: 'https://pix8.agoda.net/property/42105358/0/81094e108c7ec34e9e3579fd42204fee.jpeg?va=1&ce=0&s=1024x768', alt: 'Five-storey facade with balconies at Regenta Inn Luxinna Heights, Bhagsunag', category: 'exterior' },
      { url: 'https://pix8.agoda.net/hotelImages/42105358/-1/a568ca61cf6152ad155e417ab0233485.jpg?va=1&ce=0&s=1024x768', alt: 'Premium balcony room with valley view at Regenta Inn Luxinna Heights, Bhagsunag', category: 'room' },
      { url: 'https://pix8.agoda.net/hotelImages/42105358/-1/986283396794ddd928b1af23f6ee4e03.jpg?va=1&ce=0&s=1024x768', alt: 'Studio balcony guest room at Regenta Inn Luxinna Heights, Bhagsunag', category: 'room' },
      { url: 'https://pix8.agoda.net/hotelImages/42105358/-1/3d3b1e9ab6adb287894d2079f257cdad.jpg?va=1&ce=0&s=1024x768', alt: 'Executive balcony room with hill view at Regenta Inn Luxinna Heights, Bhagsunag', category: 'room' },
      { url: 'https://pix8.agoda.net/hotelImages/42105358/-1/93b5a420fe891891228a74de63e263d4.jpg?va=1&ce=0&s=1024x768', alt: 'Executive balcony room with queen bed at Regenta Inn Luxinna Heights, Bhagsunag', category: 'room' },
      { url: 'https://pix8.agoda.net/hotelImages/42105358/-1/620b253aa81e21ae4af99de856291055.jpg?va=1&ce=0&s=1024x768', alt: 'Guest bathroom at Regenta Inn Luxinna Heights, Bhagsunag', category: 'bathroom' },
      { url: 'https://pix8.agoda.net/property/42105358/0/c8d111acf68acd4b37d66c5bfb2d147d.jpeg?va=1&ce=0&s=1024x768', alt: 'All-day dining restaurant at Regenta Inn Luxinna Heights, Bhagsunag', category: 'restaurant' },
      { url: 'https://pix8.agoda.net/hotelImages/42105358/-1/f27e1fb75a5e4c5397e1a5258f32ef3a.jpg?va=1&ce=0&s=1024x768', alt: 'Breakfast buffet counter at Regenta Inn Luxinna Heights, Bhagsunag', category: 'restaurant' },
      { url: 'https://pix8.agoda.net/property/42105358/0/330e6bb84d2421d8799b2098d1f61559.jpeg?va=1&ce=0&s=1024x768', alt: 'Lobby lounge seating at Regenta Inn Luxinna Heights, Bhagsunag', category: 'lobby' },
    ],
    photo_source: 'https://www.agoda.com/regenta-inn-luxinna-heights-mcleodganj/hotel/dharamshala-in.html',
    check_in_time: '14:00',
    check_out_time: '12:00',
    room_types: [
      { name: 'Studio Balcony', description: 'About 24 sq m with a private balcony and mountain view.', bed_type: 'Queen' },
      { name: 'Premium Balcony', description: 'About 25 sq m with a private balcony looking over the valley.' },
      { name: 'Executive Balcony', description: 'Larger room of about 34 sq m with a private balcony and mountain view.', bed_type: 'Queen' },
    ],
    amenities: ['WiFi', 'Free parking', 'Restaurant', 'Rooftop terrace', 'Lift', 'Air conditioning', 'Heater', 'Laundry service', '24-hour front desk', 'Airport transfer', 'Balcony', 'Mountain view'],
    smoking_policy: 'Non-smoking rooms available.',
  },
  'young-monk-hostel-upper-dharamkot': {
    images: [
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/lm5vc6hrtldspzuss9ah', alt: 'Young Monk Hostel building on the Upper Dharamkot hillside', category: 'exterior' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/l5sqadjhfzria94efiar', alt: 'Yellow second wing of Young Monk Hostel among the pines, Upper Dharamkot', category: 'exterior' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/k1ezor2illagwah0yoju', alt: 'Front of Young Monk Hostel with terrace and spiral stairs, Upper Dharamkot', category: 'exterior' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/ranjl79pdifrf5vjguio', alt: 'Reception desk with Young Monk Hostel sign and Tibetan prayer flags, Upper Dharamkot', category: 'lobby' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/q6lnclpibyvesdv4unwk', alt: 'Private double room with large windows at Young Monk Hostel, Upper Dharamkot', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/hvwsz4qor7szb0mdkcog', alt: 'Wood-panelled deluxe double room with mountain view at Young Monk Hostel', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/wqa7sz3so4fgwsesvuzh', alt: 'Private room with wooden floor at Young Monk Hostel, Upper Dharamkot', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/gpulwagjhuykrre4mo0y', alt: 'Glass-partitioned private bathroom at Young Monk Hostel, Upper Dharamkot', category: 'bathroom' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/jpdfsbzidrvrbqpqkv9t', alt: 'Covered cafe terrace with forest views at Young Monk Hostel, Upper Dharamkot', category: 'restaurant' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/ntyflpakwgy7fqpgsbwt', alt: 'Common lounge and terrace seating at Young Monk Hostel, Upper Dharamkot', category: 'amenity' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/315846/vfy57hrfkil0uiny6xqn', alt: 'Balcony looking out over the Dharamkot hills at Young Monk Hostel', category: 'view' },
    ],
    photo_source: 'https://www.hostelworld.com/hostels/p/315846/young-monk-hostel-dharamkot-mecleodganj/',
    check_in_time: '13:00',
    check_out_time: '10:00',
    room_types: [
      { name: 'Standard Room', description: 'Private room in Wing A.' },
      { name: 'Deluxe Room', description: 'Larger private room in Wing A.' },
      { name: 'Premium 8-Bed Dormitory', description: 'Dorm beds in Wing A.' },
      { name: 'Dormitory (Wing B)', description: 'Additional dorm options in Wing B, next to the cafe.' },
    ],
    amenities: ['WiFi', 'Cafe', 'Restaurant', 'Outdoor terrace', 'Common room', 'Games room', 'Book exchange', 'Travel desk', 'Luggage storage', 'Linen included', '24-hour security', 'Mountain view'],
    smoking_policy: 'Smoking only in designated areas.',
  },
  'shalom-backpackers-upper-dharamkot': {
    images: [
      { url: 'https://ak-d.tripcdn.com/images/0222012000nw9kinq0343_W_1080_808_R5_Q80.jpg', alt: 'Shalom Backpackers building lit at dusk on the Upper Dharamkot hillside', category: 'exterior' },
      { url: 'https://ak-d.tripcdn.com/images/1ik1212000shrlp2829D9_W_1080_808_R5_Q80.jpg', alt: 'Shalom Backpackers Dharamkot with misty Dhauladhar slopes behind', category: 'exterior' },
      { url: 'https://ak-d.tripcdn.com/images/0226g12000nw9kio28BA2_W_1080_808_R5_Q80.jpg', alt: 'Reception desk with Shalom Backpackers sign, Upper Dharamkot', category: 'lobby' },
      { url: 'https://ak-d.tripcdn.com/images/1ik2712000shxvfpsF3EE_W_1080_808_R5_Q80.jpg', alt: 'Double room with balcony door and mountain view at Shalom Backpackers Dharamkot', category: 'room' },
      { url: 'https://ak-d.tripcdn.com/images/0226q12000nw9k5hk358D_W_1080_808_R5_Q80.jpg', alt: 'Mountain-view double room with balcony at Shalom Backpackers Dharamkot', category: 'room' },
      { url: 'https://ak-d.tripcdn.com/images/1ik2912000skhv21t25A0_W_1080_808_R5_Q80.jpg', alt: 'Private double room with forest window at Shalom Backpackers Dharamkot', category: 'room' },
      { url: 'https://ak-d.tripcdn.com/images/0225f12000nw9kjikEAA9_W_1080_808_R5_Q80.jpg', alt: 'Rooftop terrace overlooking the Dharamkot valley at Shalom Backpackers', category: 'view' },
      { url: 'https://ak-d.tripcdn.com/images/0226e12000nw9k8z16341_W_1080_808_R5_Q80.jpg', alt: 'Mural-painted common room at Shalom Backpackers Dharamkot', category: 'amenity' },
      { url: 'https://ak-d.tripcdn.com/images/0220z12000nw9kjiaD5D2_W_1080_808_R5_Q80.jpg', alt: 'Table tennis room at Shalom Backpackers, Upper Dharamkot', category: 'amenity' },
    ],
    photo_source: 'https://us.trip.com/hotels/kangra-hotel-detail-106623765/shalom-backpackers-dharamkot-mcleodganj/',
    check_in_time: '13:00',
    check_out_time: '11:00',
    room_types: [
      { name: 'Bed in 6-Bed Female Dormitory', description: 'Female-only dorm with balcony and ensuite bathroom.', bed_type: 'Single' },
      { name: 'Double Room with Balcony and Mountain View', description: 'Private double room with a balcony facing the mountains.', bed_type: 'Double' },
      { name: 'Deluxe Double Room with Balcony', description: 'Private double room with balcony, private bathroom and LCD TV.', bed_type: 'Double' },
      { name: 'Cottage with Garden View', description: 'Private cottage facing the garden.' },
    ],
    amenities: ['WiFi', 'Restaurant', 'Room service', 'Garden', 'Table tennis', 'Games area', 'Laundry service', 'Luggage storage', 'Lockers', 'Car rental', 'Currency exchange', '24-hour front desk', 'Parking', 'Mountain view'],
    smoking_policy: 'Designated smoking area.',
  },
  'eevolve-eco-hostel-dharamkot': {
    images: [
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/vxrqosatwaxok6tqczmh', alt: 'Eevolve Dharamkot hostel building in the conifer forest on Dharamkot Road', category: 'exterior' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/ebn64glk1aronn1iaw4y', alt: 'Stone-paved courtyard and covered seating at Eevolve Dharamkot', category: 'exterior' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/hp6ngkupundjmilofcic', alt: 'Garden terrace with mountain view and prayer flags at Eevolve Dharamkot', category: 'view' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/jf1jgv1fievsoro48ykf', alt: 'Glass-roofed common lounge at Eevolve Dharamkot hostel', category: 'amenity' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/rgnm64j8ppbrszrdey4d', alt: 'Private double room with forest-facing window at Eevolve Dharamkot', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/agty5mzsokhqlef3sbmy', alt: 'Spacious private room with double bed at Eevolve Dharamkot', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/dtbgujdngfxoadyaxldm', alt: 'Twin private room at Eevolve Dharamkot hostel', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/qfhbuajbglotoavciunq', alt: 'Dormitory with bunk beds and window seat at Eevolve Dharamkot', category: 'room' },
      { url: 'https://a.hwstatic.com/image/upload/f_auto,q_auto,w_1200/v1/propertyimages/3/319000/rt5heipcmyclfasibuc7', alt: 'Tiled shower room at Eevolve Dharamkot hostel', category: 'bathroom' },
    ],
    photo_source: 'https://www.hostelworld.com/hostels/p/319000/eevolve/',
    check_in_time: '13:00',
    check_out_time: '11:00',
    amenities: ['WiFi', 'Cafe', 'Coworking space', 'Free parking', 'Hot water', 'Garden', 'Outdoor terrace', 'Mountain view', 'Laundry facilities', 'Bicycle hire', 'Airport transfer', 'Lockers', 'Common room', '24-hour reception'],
  },
  'mastiff-select-mandavya-dharamkot': {
    images: [
      { url: 'https://ak-d.tripcdn.com/images/0224x12000sbytgh2F616_W_1080_808_R5_Q80.jpg', alt: 'Mastiff Select Mandavya hotel building on the forested hillside, Dharamkot', category: 'exterior' },
      { url: 'https://ak-d.tripcdn.com/images/0221o12000lz7m7rz4B44_W_1080_808_R5_Q80.jpg', alt: 'Mastiff Select Mandavya lit up at night among the deodars, Dharamkot', category: 'exterior' },
      { url: 'https://ak-d.tripcdn.com/images/1ik0h12000o3tth871A25_W_1080_808_R5_Q80.jpg', alt: 'Pool deck with Mastiff Select signage at Mandavya, Dharamkot', category: 'pool' },
      { url: 'https://ak-d.tripcdn.com/images/0227112000m5kuxbdE55B_W_1080_808_R5_Q80.jpg', alt: 'Outdoor swimming pool facing the cedar forest at Mastiff Select Mandavya', category: 'pool' },
      { url: 'https://ak-d.tripcdn.com/images/0223712000gtej02181DF_W_1080_808_R5_Q80.jpg', alt: 'Super deluxe room with forest-facing glass doors at Mastiff Select Mandavya', category: 'room' },
      { url: 'https://ak-d.tripcdn.com/images/0582u12000l2qbyic53B7_W_1080_808_R5_Q80.jpg', alt: 'Queen room with balcony at Mastiff Select Mandavya, Dharamkot', category: 'room' },
      { url: 'https://ak-d.tripcdn.com/images/1ik3612000nof9v405A3F_W_1080_808_R5_Q80.jpg', alt: 'Double-height lobby with chandeliers and forest windows at Mastiff Select Mandavya', category: 'lobby' },
      { url: 'https://ak-d.tripcdn.com/images/0223012000m5kuvs45B80_W_1080_808_R5_Q80.jpg', alt: 'In-house restaurant dining room at Mastiff Select Mandavya, Dharamkot', category: 'restaurant' },
      { url: 'https://ak-d.tripcdn.com/images/0220712000m5kuqon5A8C_W_1080_808_R5_Q80.jpg', alt: 'Restaurant seating with valley-side windows at Mastiff Select Mandavya', category: 'restaurant' },
    ],
    photo_source: 'https://us.trip.com/hotels/kangra-hotel-detail-123457382/mastiff-select-mandavya-dharamkot-mcleodganj/',
    room_types: [
      { name: 'Deluxe Room', description: 'Standard room category.' },
      { name: 'Super Deluxe Room', description: 'Room with forest-facing glass doors.', bed_type: 'Queen' },
      { name: 'Deluxe Twin Room', description: 'Room with two single beds.', bed_type: 'Twin' },
      { name: 'Premier Room', description: 'Upper room category.' },
      { name: 'Junior Suite', description: 'Suite with a king bed.', bed_type: 'King' },
      { name: 'Presidential Suite', description: 'Top suite with a king bed.', bed_type: 'King' },
    ],
    amenities: ['WiFi', 'Free parking', 'Restaurant', 'Cafe', 'Room service', 'Swimming pool', 'Lift', 'Air conditioning', 'Laundry service', 'Concierge', 'Luggage storage', '24-hour front desk', 'Balcony', 'Pet friendly'],
    smoking_policy: 'No smoking in public areas.',
  },
  'hyatt-regency-dharamshala-resort-dharamkot': {
    images: [
      { url: 'https://pix8.agoda.net/hotelImages/46045029/0/38fd8df4f008ca08d8cef376ea3a364c.jpeg?va=1&ce=0&s=1024x768', alt: 'Main building and driveway of Hyatt Regency Dharamshala Resort at dusk, Dharamkot', category: 'exterior' },
      { url: 'https://pix8.agoda.net/hotelImages/9389911/0/b6aca0de660e0b7d4a811bdf0d631a7f.jpeg?va=1&s=1024x768', alt: 'Aerial view of Hyatt Regency Dharamshala Resort in the deodar forest above the Kangra Valley', category: 'view' },
      { url: 'https://pix8.agoda.net/hotelImages/46045029/0/7864e5592e847b046dd38181afb16aa8.jpeg?va=1&ce=0&s=1024x768', alt: 'Entrance court of Hyatt Regency Dharamshala Resort among cedar trees, Dharamkot', category: 'exterior' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/579114758.jpg?k=6e689bcb1ca0f25e0e6a645e76d43d92f90e10f1bac8e46074c80485fe8fe10d&o=', alt: 'Forest villa at Hyatt Regency Dharamshala Resort, Dharamkot', category: 'exterior' },
      { url: 'https://pix8.agoda.net/hotelImages/9389911/114111522/a54fdb8c96ff2a42ab594f2549330130.jpeg?va=1&ce=3&s=1024x768', alt: 'King balcony club room at Hyatt Regency Dharamshala Resort, Dharamkot', category: 'room' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/247328958.jpg?k=aba8d33a84c1cd3fccbf53483cbe56f7bb76996a4580a01d4efe69d5b728b91b&o=', alt: 'King guest room with Tibetan-style artwork at Hyatt Regency Dharamshala Resort', category: 'room' },
      { url: 'https://pix8.agoda.net/hotelImages/9389911/-1/723ef7e83f555fe3ed1bf35d02cd3326.jpg?va=1&ca=26&ce=0&s=1024x768', alt: 'Twin-bed balcony room at Hyatt Regency Dharamshala Resort, Dharamkot', category: 'room' },
      { url: 'https://pix8.agoda.net/hotelImages/46045029/736447822/4e9bfe757f9e23156c68e5e89378796d.jpeg?va=1&ce=0&s=1024x768', alt: 'Regency Suite living room with grove view at Hyatt Regency Dharamshala Resort', category: 'room' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/247329007.jpg?k=65ef2bb5251c08cd85cd39b7cc0b50decc3092991a7177e1a8d4f7483b524dba&o=', alt: 'Heated indoor swimming pool at Hyatt Regency Dharamshala Resort, Dharamkot', category: 'pool' },
      { url: 'https://pix8.agoda.net/hotelImages/46045029/0/2f5164ae162ada0ade52423565d23ecc.jpeg?va=1&ce=0&s=1024x768', alt: 'All-day dining restaurant at Hyatt Regency Dharamshala Resort, Dharamkot', category: 'restaurant' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/232254585.jpg?k=d3968824a09eb92181fdcde8c7a69e2b64862931a881557bd0d486c858187f4b&o=', alt: 'Lobby lounge with central fireplace at Hyatt Regency Dharamshala Resort', category: 'lobby' },
      { url: 'https://pix8.agoda.net/hotelImages/9389911/0/a19521cb6373d381d69c6d4a37c3566e.jpeg?va=1&ce=3&s=1024x768', alt: 'Bar and lounge at Hyatt Regency Dharamshala Resort, Dharamkot', category: 'amenity' },
    ],
    photo_source: 'https://www.agoda.com/hyatt-regency-dharamshala-resort/hotel/dharamshala-in.html',
    check_in_time: '14:00',
    check_out_time: '12:00',
    room_types: [
      { name: '1 King Bed', description: 'About 30 sq m.', bed_type: 'King' },
      { name: '1 King Bed Balcony', description: 'About 30 sq m with a balcony and nature view.', bed_type: 'King' },
      { name: '2 Twin Beds Balcony', description: 'About 30 sq m with a balcony and nature view.', bed_type: 'Twin' },
      { name: '1 King Bed Private Garden', description: 'About 30 sq m with a private garden.', bed_type: 'King' },
      { name: '1 King Bed Balcony Club Access', description: 'About 44 sq m with balcony, nature view and club access.', bed_type: 'King' },
      { name: '2 Bedroom Residence', description: 'About 135 sq m with one king bedroom, one twin bedroom and three bathrooms.' },
      { name: '5 Bedroom Residence', description: 'Three king bedrooms and two twin bedrooms.' },
    ],
    amenities: ['WiFi', 'Free parking', 'Valet parking', 'Restaurant', 'Bar', 'Room service', 'Spa', 'Indoor swimming pool', 'Gym', 'Yoga room', 'Kids club', 'Lift', 'Garden', 'Airport transfer', '24-hour front desk'],
    smoking_policy: 'Smoke-free property with a designated smoking area.',
  },
  'chonor-house-temple-road-mcleod-ganj': {
    images: [
      { url: 'https://ak-d.tripcdn.com/images/0223312000k7b2c8s75DB_W_1080_808_R5_Q80.jpg', alt: 'Chonor House building with Tibetan window motifs and prayer flags among cedars, McLeod Ganj', category: 'exterior' },
      { url: 'https://ak-d.tripcdn.com/images/1ik1v12000t8vf43w8BF6_W_1080_808_R5_Q80.jpg', alt: 'Balconied facade of Chonor House seen through the cedar trees, Temple Road', category: 'exterior' },
      { url: 'https://norbulingka.org/cdn/shop/files/chonor-house-25x9.jpg?v=1714467728&width=1600', alt: 'Twin room with hand-painted Tibetan murals at Chonor House, McLeod Ganj', category: 'room' },
      { url: 'https://ak-d.tripcdn.com/images/0220112000k3bm9fx85B6_W_1080_808_R5_Q80.jpg', alt: 'Themed guest room with lake and bird murals at Chonor House, McLeod Ganj', category: 'room' },
      { url: 'https://ak-d.tripcdn.com/images/0226z12000k7b2i8014B6_W_1080_808_R5_Q80.jpg', alt: 'Twin room decorated with Tibetan landscape murals at Chonor House', category: 'room' },
      { url: 'https://ak-d.tripcdn.com/images/0221712000k7b1zmh083C_W_1080_808_R5_Q80.jpg', alt: 'Tibetan painted cabinet and artwork by Norbulingka artisans at Chonor House', category: 'other' },
      { url: 'https://ak-d.tripcdn.com/images/0222p12000k7b25n27C06_W_1080_808_R5_Q80.jpg', alt: 'Garden courtyard dining area at Chonor House, McLeod Ganj', category: 'restaurant' },
      { url: 'https://ak-d.tripcdn.com/images/0225c12000k7b2gof759D_W_1080_808_R5_Q80.jpg', alt: 'Sunlit dining room with long wooden table at Chonor House', category: 'restaurant' },
      { url: 'https://ak-d.tripcdn.com/images/02X4n12000dvua5ll4D3C_W_1080_808_R5_Q80.jpg', alt: 'Restaurant with Tibetan murals at Chonor House, McLeod Ganj', category: 'restaurant' },
      { url: 'https://ak-d.tripcdn.com/images/0220n12000k7b2gtt8843_W_1080_808_R5_Q80.jpg', alt: 'Lounge with Tibetan-style screens and bamboo-print cushions at Chonor House', category: 'lobby' },
    ],
    photo_source: 'https://us.trip.com/hotels/kangra-hotel-detail-110583362/chonor-house/',
    check_in_time: '12:00',
    check_out_time: '11:00',
    room_types: [
      { name: 'Superior Double or Twin Room', description: 'Individually themed room with Tibetan murals.', bed_type: 'Twin' },
      { name: 'Premium Room', description: 'Individually themed room decorated by Norbulingka artisans.' },
      { name: 'Suite Room', description: 'Suite with one queen bed and two single beds.', bed_type: 'Queen + 2 single' },
    ],
    amenities: ['WiFi', 'Free parking', 'Restaurant', 'Room service', 'Garden', 'Laundry service', 'Massage room', 'Conference room', 'Tour desk', '24-hour front desk', 'Air conditioning'],
    smoking_policy: 'No smoking in public areas; designated smoking area.',
  },
  'glenmoor-cottages-mcleod-ganj': {
    images: [
      { url: 'https://www.glenmoorcottages.com/assets/small-exterior.jpg', alt: 'Stone cottage with glazed verandah at Glenmoor Cottages, McLeod Ganj', category: 'exterior' },
      { url: 'https://www.glenmoorcottages.com/assets/aerial-cottages.jpg', alt: 'Red-roofed Glenmoor Cottages among forest trees above McLeod Ganj', category: 'exterior' },
      { url: 'https://www.glenmoorcottages.com/assets/hero-cottage.jpg', alt: 'Cottage with red trim in the deodar forest at Glenmoor Cottages', category: 'exterior' },
      { url: 'https://www.glenmoorcottages.com/assets/small-cottages.jpg', alt: 'Stone cottage and garden at Glenmoor Cottages, McLeod Ganj', category: 'exterior' },
      { url: 'https://www.glenmoorcottages.com/assets/forest-cottages.jpg', alt: 'Glenmoor cottages beneath tall trees on the wooded hillside, McLeod Ganj', category: 'view' },
    ],
    photo_source: 'https://www.glenmoorcottages.com/',
    check_in_time: '14:00',
    check_out_time: '12:00',
    room_types: [
      { name: 'Small Cottage', description: 'Independent bedroom with attached bath and a glazed verandah overlooking the forest (cottages 101-103).', bed_type: 'Two beds' },
      { name: 'Large Independent Cottage', description: 'Bedroom and attached bath with a separate sitting room on split levels (cottages 104-105).', bed_type: 'Two beds' },
      { name: 'Twin and Duplex Cottages', description: 'Neighbouring large units under one roof with sitting rooms, suited to families and groups (cottages 106-109).' },
    ],
    amenities: ['WiFi', 'Meals on order', 'Taxi service', 'Forest walking trails', 'Mountain view'],
    pet_policy: 'No pets.',
  },
  'fortune-park-moksha-satobari': {
    images: [
      { url: 'https://pix8.agoda.net/hotelImages/782079/0/8d07d5c1c90a6ae40bced2374916bbef.jpeg?va=1&ce=3&s=1024x768', alt: 'Fortune Park Moksha building on the forested Strawberry Hills, Satobari', category: 'exterior' },
      { url: 'https://pix8.agoda.net/hotelImages/782079/0/207a725748ebd5adf8a0c21442ab40e7.jpeg?va=1&ce=3&s=1024x768', alt: 'Hillside blocks and terraces of Fortune Park Moksha, Satobari near Dal Lake', category: 'exterior' },
      { url: 'https://pix8.agoda.net/hotelImages/782079/708429034/bdba9a4c5cb67775c6839d757cc5cdc9.jpeg?va=1&ce=3&s=1024x768', alt: 'Deluxe nature-view suite bedroom at Fortune Park Moksha, McLeod Ganj', category: 'room' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/865774127.jpg?k=c35de9888bfd0d8401f591cc6c5226041bf39cb9bd76abcd804f17c011d04c4e&o=', alt: 'Spacious guest room with valley-facing window at Fortune Park Moksha', category: 'room' },
      { url: 'https://pix8.agoda.net/hotelImages/782079/708429034/a72a6266b660a1598e5eccbea1bfe423.jpeg?va=1&ce=3&s=1024x768', alt: 'Suite sitting area with balcony at Fortune Park Moksha, Satobari', category: 'room' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/865781033.jpg?k=67974bff992a7b6819abbce5b1754f2d1f94d377d7d4c60b29db4c091158bd2f&o=', alt: 'Private balcony with valley views at Fortune Park Moksha, Satobari', category: 'view' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/865776018.jpg?k=54173125e9c569b331789a350248c8b0d444d52a364e972fe42f786d47ebbd9d&o=', alt: 'Glass-walled bathroom in a guest room at Fortune Park Moksha', category: 'bathroom' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/904912439.jpg?k=ad9b0d37ffb8fd7b156d269aea86855fa06b2b7730e363c7e31ceb03388e6521&o=', alt: 'Outdoor swimming pool at Fortune Park Moksha, Satobari', category: 'pool' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/38777458.jpg?k=198628e09d8f5c7cfb29439c57c7343b858b271ee2c4f667801602a0fc257b79&o=', alt: 'Restaurant with Dhauladhar mountain views at Fortune Park Moksha', category: 'restaurant' },
      { url: 'https://pix8.agoda.net/hotelImages/782079/0/6add6ba4bf0cc6f449b956270cee91fd.jpeg?va=1&ce=3&s=1024x768', alt: 'Marble lobby and reception at Fortune Park Moksha, McLeod Ganj', category: 'lobby' },
      { url: 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/38776584.jpg?k=a5ad50144cba500277b313da2015782e2b15784b88d56ea1a74dbd312fca9b92&o=', alt: 'Games room with table tennis and foosball at Fortune Park Moksha', category: 'amenity' },
    ],
    photo_source: 'https://www.agoda.com/fortune-park-moksha-hotel/hotel/dharamshala-in.html',
    check_in_time: '14:00',
    check_out_time: '12:00',
    room_types: [
      { name: 'Deluxe Valley View Room with Terrace', description: 'About 25 sq m with a terrace and valley view.', bed_type: 'Queen' },
      { name: 'Twin Room', description: 'About 25 sq m.', bed_type: 'Twin' },
      { name: 'Fortune Club Room', description: 'About 25 sq m.', bed_type: 'King' },
      { name: 'Deluxe Nature View Suite with Terrace', description: 'About 31 sq m with a terrace and nature view.', bed_type: 'Queen' },
      { name: 'Suite', description: 'About 30 sq m.', bed_type: 'King' },
      { name: 'Presidential Suite', description: 'About 63 sq m.', bed_type: 'King' },
    ],
    amenities: ['WiFi', 'Free parking', 'Outdoor swimming pool', 'Spa', 'Sauna', 'Gym', 'Restaurant', 'Bar', 'Room service', 'Lift', 'Game room', 'Babysitting', 'Air conditioning', 'Balcony', 'Airport transfer', '24-hour front desk'],
    smoking_policy: 'Non-smoking rooms; designated smoking area.',
  },
};
