import Link from 'next/link';
import { Breadcrumb } from '@/components/ui/Cards';
import { MapPin, Shield, Heart, Users, MessageCircle } from 'lucide-react';
import { generateSEO } from '@/lib/seo';
import { getWhatsAppLink } from '@/lib/utils';
import { Metadata } from 'next';
export const metadata: Metadata = generateSEO({ title: 'About Dharamshala Stay – Local Travel Experts', description: 'A local travel platform helping visitors find the best hotels, treks, and experiences in the Kangra Valley.', path: '/about' });
export default function AboutPage() {
  return (<><section className="bg-brand-900 text-white py-10"><div className="max-w-7xl mx-auto px-4 sm:px-6"><Breadcrumb items={[{ label: 'Home', href: '/' }, { label: 'About' }]} /><h1 className="text-3xl font-heading font-bold mt-2">About Us</h1></div></section><section className="max-w-3xl mx-auto px-4 sm:px-6 py-10 space-y-6"><div className="prose prose-slate prose-lg max-w-none"><p>Dharamshala Stay was born from a simple idea: travellers deserve better local support than a generic booking platform can provide.</p><p>We're a small team based in Dharamshala. We've spent years exploring every trail, testing every café, visiting every hotel, and building relationships with property owners across the region.</p><p>Our mission is straightforward: help you have the best possible experience in these mountains.</p></div><div className="grid grid-cols-2 gap-4">{[{ icon: MapPin, t: 'Local First', d: 'We live here.' }, { icon: Shield, t: 'Transparency', d: 'No hidden charges.' }, { icon: Heart, t: 'Genuine Care', d: 'Like advice from a friend.' }, { icon: Users, t: 'Community', d: 'Supporting local families.' }].map(v => <div key={v.t} className="bg-slate-50 rounded-xl p-4 border"><v.icon className="h-5 w-5 text-brand-600 mb-2" /><h3 className="font-semibold text-slate-900">{v.t}</h3><p className="text-sm text-slate-600">{v.d}</p></div>)}</div><div className="bg-blue-50 rounded-xl p-6 text-center"><h3 className="text-lg font-heading font-bold mb-2">Get in Touch</h3><div className="flex justify-center gap-3"><Link href="/contact" className="bg-brand-600 text-white px-5 py-2.5 rounded-lg font-medium hover:bg-brand-700">Contact Us</Link><a href={getWhatsAppLink()} target="_blank" rel="noopener noreferrer" className="bg-green-500 text-white px-5 py-2.5 rounded-lg font-medium hover:bg-green-600 flex items-center gap-1"><MessageCircle className="h-4 w-4" /> WhatsApp</a></div></div></section></>);
}
