import type { Trek } from '@/types';

/**
 * 8 additional guided treks. Facts follow the researched trek guides in
 * data/blog-posts-w2.ts, data/blog-posts-c.ts, data/blog.ts and data/faqs-extra-1.ts.
 * Altitudes and distances are approximate; 2026 rules (Kangra DDMA order of Jan 2026,
 * Rs.500 refundable waste deposit on the Triund route since 11 Aug 2026) are noted where relevant.
 */
export const newTreks: Omit<Trek, 'id' | 'created_at' | 'updated_at'>[] = [
  // ───────────────────────── 1. INDRAHAR PASS ─────────────────────────
  {
    slug: 'indrahar-pass-trek',
    name: 'Indrahar Pass Trek',
    destination_slug: 'dharamkot',
    difficulty: 'expert',
    duration: '3-4 Days',
    distance: 'Approx. 28-32 km round trip',
    max_altitude: 'Approx. 4,342 m',
    best_season: 'Late May-June, mid-Sep-Oct (subject to 2026 district rules)',
    price_per_person: 11000,
    group_discount: 'Price for groups of 4 or more; smaller groups and the Chamba-side crossing are quoted separately.',
    short_description: 'The high crossing of the Dhauladhar above McLeod Ganj: Triund, Laka Got and the Lahesh caves, then a pre-dawn climb over boulders and scree to Indrahar Pass at approx. 4,342 m.',
    description: 'Indrahar Pass is the big one above McLeod Ganj. From Gallu Devi temple the route climbs to Triund, follows the rocky ridge past Snowline and Laka Got below the Laka glacier, and camps at the Lahesh caves, the old Gaddi shepherd shelters at approx. 3,500-3,600 m. Summit day starts around 4 or 5 am and climbs a long boulder-and-scree slope to the narrow notch of the pass, where on a clear morning you see the Kangra Valley on one side and the Pir Panjal and Mani Mahesh Kailash range on the other. Our standard trip goes out and back to McLeod Ganj; the crossing to the Chamba side via Chhata and Kuarsi can be arranged on request with extra days and transport.\n\nThis is a difficult, high-altitude trek, not "Triund plus a bit". It suits fit trekkers who have done at least one multi-day Himalayan trek and are comfortable on boulders. Please note: in January 2026 the Kangra District Disaster Management Authority banned trekking above 3,000 m in the district, and we could not confirm whether that order has been relaxed for the autumn season. We run this trek only when it is permitted and confirm the current position before taking any payment. Our guides follow a strict turn-around rule (at the pass by about 11 am, or we turn back), and every trekker on the Triund route pays the refundable Rs.500 waste deposit at the forest checkpost.',
    itinerary: [
      { day: 1, title: 'Gallu Devi to Triund', description: 'Meet in McLeod Ganj or Dharamkot and start from Gallu Devi temple (approx. 2,100 m). Climb 6-7 km through oak and rhododendron forest, past the forest checkpost and Magic View cafe area, to Triund. Sleeping at Triund rather than pushing higher helps acclimatisation. Camp, dinner and briefing.', distance: '6-7 km', altitude: '2,850 m' },
      { day: 2, title: 'Triund to Lahesh caves via Snowline and Laka Got', description: 'Climb the rocky ridge to Snowline and Laka Got at the foot of the Laka glacier, then scramble over steep, loose ground and small streams to the Lahesh caves. Camp in tents near the caves. This is the last reliable water before the pass, so we fill up and treat water here.', distance: 'Approx. 5-7 km', altitude: 'Approx. 3,500-3,600 m' },
      { day: 3, title: 'Summit day: Indrahar Pass and back to Lahesh or Laka Got', description: 'Start by 4-5 am with headlamps. Climb 4-6 hours over boulders and scree (possibly hard snow early in the season) to the pass, spend 20-30 minutes at the small shrine, and descend before cloud builds. If we are not at the pass by about 11 am or the weather closes in, we turn back. Overnight at Lahesh or Laka Got.', distance: 'Approx. 5-6 km round trip', altitude: 'Approx. 4,342 m' },
      { day: 4, title: 'Descent to McLeod Ganj', description: 'Walk down past Triund to Gallu Devi and Dharamkot, collect your waste deposit refund at the checkpost on the way, and finish in McLeod Ganj by afternoon. Very fit groups in settled weather may compress the trek into 3 days; we decide this on the mountain.', distance: 'Approx. 12-14 km', altitude: '1,750 m' },
    ],
    includes: ['Experienced local trek leader and support staff', 'Tents, sleeping bags rated to approx. -5 °C and mats', 'All meals on the trek from day 1 lunch to day 4 lunch', 'Forest entry fees', 'Help with district permission or clearance where required', 'First aid kit and emergency plan', 'Porters or mules for group camping kit (lower section)'],
    excludes: ['Transport to Dharamkot / Gallu Devi', 'Rs.500 refundable waste deposit at the Triund checkpost (paid by each trekker, returned on descent)', 'Chamba-side crossing, extra days and return transport from Chamba', 'Personal porter', 'Travel and rescue insurance', 'Tips', 'Personal gear and medicines'],
    things_to_carry: ['Ankle-high trekking boots with good grip', 'Microspikes (May-early June and October)', 'Thermal base layers, fleece and down jacket', 'Waterproof jacket and trousers', 'Warm hat and gloves', '2-3 litre water capacity plus filter or tablets', 'Headlamp with spare batteries', 'Trekking poles', 'Sunscreen SPF 50, UV sunglasses, lip balm', 'Personal medicines and blister kit', 'Photo ID and cash'],
    images: [],
    featured: false,
    faqs: [
      { question: 'Is the Indrahar Pass trek allowed in 2026?', answer: 'In January 2026 the Kangra District Disaster Management Authority banned trekking above 3,000 m in the district, which covers Indrahar Pass. We could not confirm whether the order has been lifted for autumn 2026. We only run the trek when it is permitted and will confirm the current position before you pay.' },
      { question: 'How difficult is Indrahar Pass?', answer: 'It is a difficult high-altitude trek. It is non-technical in good conditions, but summit day from the Lahesh caves means 8 to 12 hours on steep boulders and scree, with sudden storms possible. If Triund felt hard, or you have never been above about 3,500 m, choose Snowline and Laka Got instead.' },
      { question: 'Can we cross over to the Chamba side?', answer: 'Yes, on request. The crossing via Chhata and Kuarsi adds a day or two and needs a pre-arranged jeep pick-up near Machhetar; the drive back to Dharamshala from Chamba is long (approx. 6 to 8 hours). We quote it separately.' },
      { question: 'What happens if the weather turns?', answer: 'Our guides turn back if we are not at the pass by about 11 am or if cloud and storms close in. Mountain weather here usually clouds over by late morning. Safety comes before the summit, and we cannot refund for weather turn-arounds, though we always try to reschedule.' },
    ],
    status: 'published',
    meta_title: 'Indrahar Pass Trek 2026: Guided 4-Day Trip from McLeod Ganj',
    meta_description: 'Guided Indrahar Pass trek (approx. 4,342 m) from McLeod Ganj via Triund and Lahesh caves. Tents, meals, expert guide and 2026 permission check included.',
  },

  // ───────────────────────── 2. TRIUND – SNOWLINE – LAKA GOT ─────────────────────────
  {
    slug: 'triund-snowline-laka-got-trek',
    name: 'Triund to Snowline & Laka Got Trek',
    destination_slug: 'dharamkot',
    difficulty: 'moderate',
    duration: '2 Days',
    distance: 'Approx. 18-22 km round trip',
    max_altitude: 'Approx. 3,350 m',
    best_season: 'April-June, mid-Sep-Oct (subject to 2026 district rules)',
    price_per_person: 3500,
    short_description: 'Go one step beyond the Triund crowds: camp on the Triund ridge, then walk at dawn to Snowline and Laka Got at the foot of the Laka glacier, right under the Dhauladhar wall.',
    description: 'This is the best-value extension in the area. Day one is the classic walk from Gallu Devi temple above Dharamkot to the Triund ridge (approx. 2,850 m) and a night in a camp with sunset over the Kangra Valley. On day two we leave early, walk 2-3 km up the rocky ridge to Snowline (approx. 3,100-3,200 m) and about 1 km further to Laka Got (approx. 3,350 m), a bowl of boulders and grass below the Laka glacier, before the afternoon cloud rolls in. Then it is back to Triund for breakfast and down to Dharamkot by late afternoon.\n\nAbove Triund the trail is steeper, rockier and much quieter, and the view of the granite wall changes completely. Snow is usually present until about May; by autumn you may see little at Snowline, though the glacier keeps some ice. Two 2026 rules apply: since 11 August 2026 every trekker pays a refundable Rs.500 waste deposit at the forest checkpost, and in January 2026 the Kangra DDMA banned trekking above 3,000 m and placed Triund under a police-clearance requirement. We could not confirm whether that order has been relaxed, so we check before every departure; if the higher section is closed, Triund becomes the turn-around point and we refund the price difference.',
    itinerary: [
      { day: 1, title: 'Gallu Devi to Triund camp', description: 'Start around 9 am from Gallu Devi temple above Dharamkot. Climb through oak and rhododendron forest to the Magic View cafe area, then up the steep final switchbacks to Triund (6-7 km, 3-5 hours). Tents, sunset, dinner and an early night.', distance: '6-7 km', altitude: '2,850 m' },
      { day: 2, title: 'Dawn walk to Snowline and Laka Got, then descent', description: 'Leave camp at first light, walk 1-1.5 hours to Snowline and another 45 minutes to 1 hour to Laka Got. We stay well away from the cliffs and gullies (rockfall) and are back below Snowline by about noon. Return to Triund for a late breakfast, pack up and descend to Dharamkot, collecting your waste deposit refund at the checkpost.', distance: 'Approx. 12-15 km', altitude: 'Approx. 3,350 m' },
    ],
    includes: ['Local trek guide', 'Tent, sleeping bag and mat at a permitted Triund camp', 'Dinner, breakfast and evening tea', 'Forest entry fees', 'Help with district clearance where required', 'First aid kit'],
    excludes: ['Transport to Dharamkot / Gallu Devi', 'Rs.500 refundable waste deposit (paid by each trekker at the checkpost)', 'Lunch and snacks from Triund shacks', 'Porter', 'Insurance', 'Tips'],
    things_to_carry: ['Trekking shoes with grip (not running shoes)', 'Microspikes in April-May', 'Down jacket, fleece and windproof layer', 'Warm hat and gloves', '2 litres of water and snacks', 'Rain jacket', 'Headlamp and power bank', 'Sunscreen and sunglasses', 'Photo ID and cash'],
    images: [],
    featured: false,
    faqs: [
      { question: 'How far is Snowline from Triund?', answer: 'About 2 to 3 km above Triund, roughly 1 to 1.5 hours of steady uphill walking. Laka Got, at the foot of the Laka glacier, is about 1 km further.' },
      { question: 'Will there be snow at Snowline?', answer: 'Snow is usually present from winter until about May, sometimes June. In autumn you may see little or none at Snowline, though the Laka glacier above Laka Got keeps some snow and ice.' },
      { question: 'Is Snowline open in 2026?', answer: 'Snowline and Laka Got lie above 3,000 m. A January 2026 Kangra DDMA order banned trekking above that height and put Triund under police clearance. We could not confirm whether it has been relaxed, so we check before each departure; if the upper section is closed we stop at Triund and refund the difference.' },
      { question: 'What is the Rs.500 deposit?', answer: 'Since 11 August 2026 trekkers on the Triund route pay a refundable Rs.500 deposit at the forest checkpost and get a garbage bag. Bring your non-biodegradable waste back down and the deposit is returned.' },
    ],
    status: 'published',
    meta_title: 'Triund to Snowline & Laka Got Trek: 2-Day Guided Camp',
    meta_description: 'Guided 2-day trek from Dharamkot: camp at Triund, then a dawn walk to Snowline and Laka Got below the Laka glacier. Tent, meals and guide from Rs.3,500.',
  },

  // ───────────────────────── 3. GUNA DEVI ─────────────────────────
  {
    slug: 'guna-devi-temple-hike',
    name: 'Guna Devi Temple Hike',
    destination_slug: 'dharamkot',
    difficulty: 'moderate',
    duration: 'Day hike (5-7 hours)',
    distance: 'Approx. 10-12 km round trip from Dharamkot',
    max_altitude: 'Approx. 2,500 m (sources vary)',
    best_season: 'March-June, Sep-Nov',
    price_per_person: 1500,
    short_description: 'A quiet forest climb from Dharamkot to the small hilltop shrine of Guna Devi (Guna Mata), with wide Kangra Valley views and a fraction of the Triund crowds.',
    description: 'Guna Devi, also called Guna Mata, is a small shrine on a forested ridge above Dharamkot and McLeod Ganj. The trail climbs steadily through oak and rhododendron forest, past Gaddi grazing slopes, to a clearing with prayer flags and wide views over the Kangra Valley and back towards the Dhauladhar. It is the hike locals suggest when someone asks for a "quiet Triund": less height, far fewer people and a real sense of being in the forest.\n\nThe path is not well marked and has several forks, which is why we run it with a local guide who knows the current route. Expect roughly 3 to 4 hours up depending on your pace and starting point, and a little less coming down. Most of the route is easy to moderate, with a few steep, stony sections. It makes a good warm-up before Triund or a rest-day outing for people who want something more than a town walk. Distances and the exact altitude vary between sources, so treat the figures here as approximate.',
    itinerary: [
      { day: 1, title: 'Dharamkot to Guna Devi and back', description: 'Meet at 8 am in Dharamkot. Climb through the forest to Guna Devi temple (approx. 3-4 hours with breaks), with time at the shrine for a packed lunch and the view. Descend by the same or a parallel path and be back in Dharamkot by mid-afternoon, well before dark.', distance: 'Approx. 10-12 km round trip', altitude: 'Approx. 2,500 m' },
    ],
    includes: ['Local guide who knows the current route', 'Packed lunch and tea', 'Bottled water refill', 'First aid kit'],
    excludes: ['Transport to Dharamkot', 'Snacks at cafes', 'Tips', 'Insurance'],
    things_to_carry: ['Trainers or trekking shoes with grip', '1.5-2 litres of water', 'Light warm layer', 'Rain jacket (spring and autumn)', 'Sun cap and sunscreen', 'Cash'],
    images: [],
    featured: false,
    faqs: [
      { question: 'Can I hike to Guna Devi without a guide?', answer: 'Some people do, but the trail is not well marked and has several branches, so it is easy to lose the route in fog. We recommend going with a local guide, starting early and never attempting it late in the day.' },
      { question: 'Is the Guna Devi hike suitable for children?', answer: 'It is not ideal for young children because of the length and a few steep sections. Fit teenagers who enjoy walking usually manage well. For families with small kids we suggest Dal Lake, the Lingkhor kora or the Gallu Devi sunrise walk.' },
      { question: 'Do I need a permit or pay the Triund deposit?', answer: 'No special permit has generally been needed, and this route does not pass the Triund checkpost where the Rs.500 waste deposit is collected. Please still carry all your rubbish back down.' },
    ],
    status: 'published',
    meta_title: 'Guna Devi Temple Hike from Dharamkot: Guided Day Trek',
    meta_description: 'Guided day hike to Guna Devi (Guna Mata) temple above Dharamkot: quiet forest trail, Kangra Valley views, fewer crowds than Triund. Packed lunch included.',
  },

  // ───────────────────────── 4. THATHARANA ─────────────────────────
  {
    slug: 'thatharana-trek',
    name: 'Thatharana Trek',
    destination_slug: 'dharamshala',
    difficulty: 'moderate',
    duration: '2 Days',
    distance: 'Approx. 14-18 km round trip',
    max_altitude: 'Approx. 2,900 m (sources vary)',
    best_season: 'April-June, mid-Sep-Nov',
    price_per_person: 4000,
    short_description: 'A steep, little-known climb from the Khaniyara side of Dharamshala to a high meadow on the Dhauladhar flank, with an overnight camp and big views and almost nobody else around.',
    description: 'Thatharana is the trek for people who want Triund-style views without the Triund crowds. The trail starts on the Khaniyara side of Dharamshala, east of the town, and climbs steeply through forest and Gaddi grazing land to a ridge-top meadow facing the Dhauladhar wall, with the whole Kangra Valley spread out below. We camp near the top, watch sunset and sunrise over the valley, and walk back down the next morning.\n\nIt is rated moderate for a 2-day pace, but the climb is relentless and the trail is not well marked, so it is not a beginner walk: you should be comfortable with 5 to 6 hours of steep uphill. Water sources on the route are limited and seasonal, so our team carries water and camp kit. Expect approx. 7 to 9 km one way; altitude figures vary between sources. The meadow sits close to the 3,000 m line in the January 2026 Kangra DDMA order on high-altitude trekking, so we confirm current access with the authorities before each departure.',
    itinerary: [
      { day: 1, title: 'Khaniyara side to Thatharana meadow', description: 'Pick-up in Dharamshala and short drive to the trailhead on the Khaniyara side. Steep climb through forest and open slopes with rest stops and a packed lunch (approx. 5-6 hours). Set up camp on the meadow, sunset over the Kangra Valley, hot dinner.', distance: 'Approx. 7-9 km', altitude: 'Approx. 2,900 m' },
      { day: 2, title: 'Sunrise and descent to Dharamshala', description: 'Sunrise over the Dhauladhar and valley, breakfast, then a careful descent on the same trail (approx. 3-4 hours). Drop back to your hotel in Dharamshala or McLeod Ganj by afternoon.', distance: 'Approx. 7-9 km', altitude: 'Down to approx. 1,300 m' },
    ],
    includes: ['Local trek guide and camp staff', 'Return transfer from Dharamshala to the trailhead', 'Tents, sleeping bags and mats', 'Packed lunch day 1, dinner, breakfast', 'Water for the camp', 'Forest or local fees where applicable', 'First aid kit'],
    excludes: ['Personal porter', 'Snacks and drinks beyond meals listed', 'Insurance', 'Tips'],
    things_to_carry: ['Trekking shoes with good grip', 'Trekking poles (steep descent)', '2 litres of water', 'Warm fleece and down jacket', 'Rain jacket', 'Headlamp', 'Sunscreen and cap', 'Personal medicines', 'Photo ID'],
    images: [],
    featured: false,
    faqs: [
      { question: 'How is Thatharana different from Triund?', answer: 'Thatharana has similar big Dhauladhar and Kangra Valley views but far fewer people. The climb is steeper and the trail less marked, and there are no tea shacks or facilities on the way, so it feels much wilder.' },
      { question: 'Can Thatharana be done in one day?', answer: 'Very fit hikers sometimes do it as a long day, but it is approx. 7 to 9 km each way with a steep climb. We recommend the overnight so you get sunset and sunrise and a gentler pace.' },
      { question: 'Is Thatharana affected by the 2026 trekking rules?', answer: 'It lies close to the 3,000 m line in the January 2026 Kangra DDMA order on high-altitude treks. We check the current position with the authorities before each departure and will reschedule or refund if access is not allowed.' },
    ],
    status: 'published',
    meta_title: 'Thatharana Trek from Dharamshala: 2-Day Guided Camp',
    meta_description: 'Guided 2-day Thatharana trek from the Khaniyara side of Dharamshala: steep climb, meadow camp, Dhauladhar sunrise and no crowds. Tents, meals and transfer.',
  },

  // ───────────────────────── 5. BIR BILLING – RAJGUNDHA ─────────────────────────
  {
    slug: 'bir-billing-rajgundha-trek',
    name: 'Bir Billing to Rajgundha Trek',
    destination_slug: 'dharamshala',
    difficulty: 'moderate',
    duration: '2-3 Days',
    distance: 'Approx. 24-30 km round trip from Billing',
    max_altitude: 'Approx. 2,600-2,800 m (sources vary)',
    best_season: 'April-June, mid-Sep-Nov',
    price_per_person: 4500,
    group_discount: 'Price is for the 2-day return; the 3-day option via Barot is quoted on request.',
    short_description: 'From the Billing paragliding take-off, walk through oak, rhododendron and deodar forest and open meadows into the remote Chhota Bhangal valley, and spend the night in a Rajgundha village homestay.',
    description: 'The Billing to Rajgundha trek starts at the paragliding take-off at Billing (approx. 2,400 m), 14 km above Bir, and follows forest and meadow trails over the ridge into the Chhota Bhangal valley. After the high point the forest opens into grassy slopes dotted with Gaddi shepherd huts, before dropping to Rajgundha (approx. 2,400-2,500 m), a small village of wooden and slate houses and terraced fields facing the high Dhauladhar. It is roughly 12 to 15 km one way, 5 to 7 hours of walking, long but never technical.\n\nWe stay in a simple village homestay with home-cooked dal, rice and roti, then walk back to Billing on day two, or, on the 3-day version, continue down the valley towards Badagran and Barot on the Uhl river. Rajgundha has weak or no mobile signal and no ATM, and the route stays below 3,000 m, so it has generally not needed a special trekking permit, though local fees can apply and rules change. It pairs perfectly with a paragliding flight in Bir: fly on arrival day while the weather is clear, then trek.',
    itinerary: [
      { day: 1, title: 'Bir to Billing by taxi, trek to Rajgundha', description: '8 am taxi from Bir up the 14 km mountain road to Billing. Trek northeast through oak, rhododendron and deodar forest to the ridge, across shepherd meadows and down to Rajgundha (5-7 hours). Homestay dinner and an evening in the village.', distance: 'Approx. 12-15 km', altitude: 'Approx. 2,400-2,500 m' },
      { day: 2, title: 'Rajgundha back to Billing and Bir', description: 'Sunrise walk around the village, breakfast, then retrace the trail to Billing and drive down to Bir by evening. On the 3-day option you instead walk or take a jeep (track conditions permitting) towards Badagran and Barot and stay the night in Barot.', distance: 'Approx. 12-15 km', altitude: 'Approx. 2,700 m on the ridge' },
      { day: 3, title: 'Optional: Barot to Bir or Dharamshala', description: 'For the 3-day version only: trout farm and riverside walk in Barot, then drive back to Bir, Mandi or Dharamshala. Transport on the Barot side must be confirmed in advance.' },
    ],
    includes: ['Local guide', 'Taxi Bir to Billing (day 1) and Billing to Bir (day 2)', 'Village homestay with dinner and breakfast', 'Packed lunch on trek days', 'First aid kit'],
    excludes: ['Transfer between Dharamshala and Bir (approx. 2-2.5 hours; we can arrange)', 'Paragliding', '3-day Barot extension, Barot stay and transport', 'Insurance', 'Tips', 'Local camping or panchayat fees if applicable'],
    things_to_carry: ['Trekking shoes with grip', 'Rain jacket', 'Warm fleece, plus a down jacket from October', 'Headlamp and power bank', 'Cash (no ATMs or card payments in Rajgundha)', 'Water bottle and filter or tablets', 'Toiletries and small towel', 'Sunscreen, cap and sunglasses'],
    images: [],
    featured: false,
    faqs: [
      { question: 'How long is the Billing to Rajgundha trek?', answer: 'Roughly 12 to 15 km one way depending on the exact route, about 5 to 7 hours of walking. Our 2-day trip stays a night in Rajgundha and returns to Billing; the 3-day option continues to Barot.' },
      { question: 'Is the Rajgundha trek difficult?', answer: 'It is easy to moderate. The climb from Billing is gradual and there is no technical ground, but it is a long day, so you should be comfortable walking 5 to 7 hours.' },
      { question: 'Can I combine it with paragliding?', answer: 'Yes, and we recommend it. Fly from Billing on your arrival day in Bir while the weather is clear, then start the trek the next morning. Paragliding is booked separately.' },
      { question: 'Is this the same as the Thamsar Pass trek?', answer: 'No. Rajgundha is the first night on the Thamsar Pass route, but Thamsar crosses well above 4,000 m and is a serious expedition. This trip is a gentle village walk that stays below 3,000 m.' },
    ],
    status: 'published',
    meta_title: 'Bir Billing to Rajgundha Trek: 2-Day Guided Homestay Trip',
    meta_description: 'Guided Billing to Rajgundha trek: forest and meadow trail into Chhota Bhangal, village homestay, taxi to Billing and meals included. Barot option on request.',
  },

  // ───────────────────────── 6. GALLU DEVI SUNRISE ─────────────────────────
  {
    slug: 'dharamkot-gallu-devi-sunrise-hike',
    name: 'Dharamkot to Gallu Devi Sunrise Hike',
    destination_slug: 'dharamkot',
    difficulty: 'easy',
    duration: 'Half day (3-4 hours)',
    distance: 'Approx. 3-4 km round trip from Dharamkot',
    max_altitude: 'Approx. 2,150 m',
    best_season: 'Year-round in clear weather; best Oct-Mar for views',
    price_per_person: 1200,
    short_description: 'An early-morning walk from Dharamkot up to Gallu Devi temple, where the Triund trail begins, to watch first light on the Dhauladhar and the Kangra Valley over hot chai.',
    description: 'Gallu Devi (also spelt Galu) is the small temple above Upper Dharamkot where the Triund trek officially begins. In daylight it is a pleasant warm-up walk; before dawn it becomes one of the nicest short outings in the area. We meet in Dharamkot in the dark, climb 1.5 to 2 km of steady uphill path by headlamp, and reach the temple area in time to watch the light come up over the valley and turn the high Dhauladhar pink and gold. Breakfast and chai follow, then an easy stroll back down to the village cafes.\n\nIt is a short walk, but the path is steady uphill and stony, so we rate it easy with a little effort. It is a great option for families, first-timers, people on a rest day before Triund, or anyone who wants mountain views without committing to a full trek. We stay at Gallu Devi and do not go beyond the forest checkpost, so the Triund entry fee and the Rs.500 waste deposit (in force since 11 August 2026) do not apply unless you choose to extend towards Magic View, which we can arrange.',
    itinerary: [
      { day: 1, title: 'Pre-dawn walk to Gallu Devi and back', description: 'Meet in Dharamkot about 45-60 minutes before sunrise (roughly 5 am in summer, 6 am in winter). Walk up by headlamp to Gallu Devi temple (approx. 45 minutes to 1 hour), watch the sunrise, breakfast with chai, and stroll back down to Dharamkot by mid-morning. Pick-up from McLeod Ganj can be arranged.', distance: 'Approx. 3-4 km round trip', altitude: 'Approx. 2,150 m' },
    ],
    includes: ['Local guide', 'Headlamp on loan if needed', 'Breakfast and chai', 'First aid kit'],
    excludes: ['Taxi from McLeod Ganj or Bhagsu to Dharamkot', 'Extension beyond Gallu Devi (forest fee and Rs.500 refundable waste deposit apply)', 'Tips'],
    things_to_carry: ['Trainers with grip', 'Warm jacket, hat and gloves (mornings are cold)', 'Small water bottle', 'Camera', 'Cash for extra snacks'],
    images: [],
    featured: false,
    faqs: [
      { question: 'How hard is the walk to Gallu Devi?', answer: 'It is short, about 1.5 to 2 km from Dharamkot, but steadily uphill on a stony path. Most people with basic fitness, including older children, manage it comfortably at a slow pace.' },
      { question: 'What time does the hike start?', answer: 'About 45 to 60 minutes before sunrise, so roughly 5 am in summer and 6 am in winter. We confirm the exact time the evening before based on the weather forecast.' },
      { question: 'What if it is cloudy?', answer: 'Dhauladhar views depend on the weather. If the forecast is poor we offer to move the hike to the next clear morning; October to March usually gives the clearest skies.' },
    ],
    status: 'published',
    meta_title: 'Gallu Devi Sunrise Hike from Dharamkot: Guided Walk',
    meta_description: 'Guided pre-dawn walk from Dharamkot to Gallu Devi temple, start of the Triund trail, for sunrise over the Dhauladhar and Kangra Valley. Breakfast included.',
  },

  // ───────────────────────── 7. MINKIANI PASS ─────────────────────────
  {
    slug: 'minkiani-pass-trek',
    name: 'Minkiani Pass Trek via Kareri Lake',
    destination_slug: 'dharamshala',
    difficulty: 'hard',
    duration: '4-5 Days',
    distance: 'Approx. 36-40 km round trip',
    max_altitude: 'Approx. 4,250 m (sources vary)',
    best_season: 'Late May-June, mid-Sep-Oct (subject to 2026 district rules)',
    price_per_person: 14500,
    group_discount: 'Price for groups of 4 or more; crossing to the Chamba side is quoted separately.',
    short_description: 'Follow the Nyund stream to the glacial Kareri Lake (approx. 2,934 m), then climb into the boulder country beyond it to Minkiani Pass, a high Dhauladhar crossing towards the Chamba side.',
    description: 'Minkiani Pass sits on the Dhauladhar crest above Kareri Lake, whose clear, shallow water is fed by snowmelt from the Minkiani area. The first two days are the classic Kareri Lake trek: from Kareri village along the Nyund stream through oak and pine forest to the meadow at Reoti, then up the bouldery upper valley to the lake and its small Shiva temple. From there the trail climbs steeply into rough, rocky terrain to a high camp below the pass, and summit day crosses boulder fields and, early in the season, old snow to the pass itself.\n\nThis is a much harder, high-altitude trek than Kareri Lake and needs an experienced guide and proper gear. Our standard trip goes to the pass and returns to Kareri village, with buffer for weather; a crossing to the Chamba side can be arranged on request. The Kareri route passes through Dhauladhar Wildlife Sanctuary forest land, where a forest permit has generally been required, and in January 2026 the Kangra DDMA banned trekking above 3,000 m and routed permission for Kareri through the Superintendent of Police, Kangra. We could not confirm whether that order has been relaxed, so we run this trek only when it is permitted and confirm before taking payment. Altitude figures for the pass vary between sources.',
    itinerary: [
      { day: 1, title: 'Dharamshala to Kareri village and Reoti', description: 'Drive 1-1.5 hours via Ghera to the roadhead near Kareri village (approx. 1,800 m). Trek along the Nyund stream over log bridges through mixed forest to the Reoti meadow (approx. 6 km, 4-5 hours). Camp.', distance: 'Approx. 6 km', altitude: 'Approx. 2,300 m' },
      { day: 2, title: 'Reoti to Kareri Lake', description: 'Climb over boulders along the stream, with stone-paved sections and a steeper last stretch, to Kareri Lake (approx. 7 km, 3.5-5 hours). Camp on the grassy flats by the lake. Afternoon rest for acclimatisation.', distance: 'Approx. 7 km', altitude: 'Approx. 2,934 m' },
      { day: 3, title: 'Kareri Lake to high camp below Minkiani', description: 'Steep climb on rough, rocky ground above the lake to a high camp below the pass. Short day for acclimatisation; early dinner and briefing for summit day.', distance: 'Approx. 4-5 km', altitude: 'Approx. 3,600-3,700 m' },
      { day: 4, title: 'Summit day: Minkiani Pass and back to Kareri Lake', description: 'Pre-dawn start over boulder fields and possible snow to Minkiani Pass, views over the Dhauladhar towards the Chamba side, then descend before the afternoon cloud. Strict turn-around time. Overnight at Kareri Lake.', distance: 'Approx. 9-10 km', altitude: 'Approx. 4,250 m' },
      { day: 5, title: 'Kareri Lake to Kareri village and Dharamshala', description: 'Long descent past Reoti to Kareri village (5-7 hours) and drive back to Dharamshala or McLeod Ganj by evening.', distance: 'Approx. 13 km', altitude: 'Approx. 1,800 m' },
    ],
    includes: ['Experienced high-altitude trek leader, cook and support staff', 'Return transport Dharamshala to Kareri roadhead', 'Tents, sleeping bags rated to approx. -5 °C and mats', 'All meals on the trek', 'Forest permits and help with district clearance where required', 'Porters or mules for group kit', 'First aid kit and emergency plan'],
    excludes: ['Chamba-side crossing and return transport from Chamba', 'Personal porter', 'Travel and rescue insurance', 'Tips', 'Personal gear and medicines', 'Hotel stays before and after the trek'],
    things_to_carry: ['Ankle-high trekking boots with good grip', 'Microspikes (early season and October)', 'Thermal base layers, fleece and down jacket', 'Waterproof jacket and trousers', 'Warm hat and gloves', '2-3 litre water capacity plus filter or tablets', 'Headlamp with spare batteries', 'Trekking poles', 'Sunscreen SPF 50 and UV sunglasses', 'Personal medicines', 'Photo ID and cash'],
    images: [],
    featured: false,
    faqs: [
      { question: 'How is Minkiani different from the Kareri Lake trek?', answer: 'The first two days are the same. Kareri Lake (approx. 2,934 m) is easy to moderate; Minkiani continues well above 4,000 m on steep, rocky and sometimes snowy ground. It needs prior multi-day trekking experience, good fitness and acclimatisation.' },
      { question: 'Is the Minkiani Pass trek allowed in 2026?', answer: 'The pass lies far above 3,000 m. In January 2026 the Kangra DDMA banned trekking above that height and routed Kareri permissions through the SP Kangra office. We could not confirm whether the order has been relaxed, so we confirm before every booking and run the trek only if permitted.' },
      { question: 'Do I need a permit?', answer: 'A forest entry permit has generally been required because the route crosses Dhauladhar Wildlife Sanctuary forest land, and district clearance may be needed under the 2026 rules. We arrange both where required. Carry a government photo ID.' },
      { question: 'Can we cross to the Chamba side?', answer: 'On request, with extra days and pre-arranged transport on the far side. Our standard itinerary returns via Kareri Lake, which is simpler and keeps a buffer for weather.' },
    ],
    status: 'published',
    meta_title: 'Minkiani Pass Trek via Kareri Lake: 5-Day Guided Trek',
    meta_description: 'Guided 5-day Minkiani Pass trek from Dharamshala via Reoti and Kareri Lake to a high Dhauladhar pass. Tents, meals, permits and expert guide included.',
  },

  // ───────────────────────── 8. ADI HIMANI CHAMUNDA ─────────────────────────
  {
    slug: 'adi-himani-chamunda-trek',
    name: 'Adi Himani Chamunda Trek',
    destination_slug: 'dharamshala',
    difficulty: 'hard',
    duration: '1 Day (overnight option)',
    distance: 'Approx. 14-18 km round trip',
    max_altitude: 'Approx. 2,700-2,800 m (sources vary)',
    best_season: 'April-June, Sep-Nov',
    price_per_person: 2000,
    group_discount: 'Day-hike price; the overnight option with camping is quoted on request.',
    short_description: 'A long, steep pilgrimage trail up the Dhauladhar flank above Chamunda Devi to the high hilltop shrine of Adi Himani Chamunda, believed to be the original seat of the goddess.',
    description: 'Adi Himani Chamunda is a hilltop shrine high on the Dhauladhar ridge above the well-known Chamunda Devi temple on the Baner river, about 15 km from Dharamshala on the Palampur road. Local tradition holds it to be the original seat of the goddess, and devotees still climb to it on foot. The trail rises steeply through forest and open slopes, with the Kangra Valley opening up below and the snow peaks close above. It is a meaningful trek for pilgrims and a quiet, demanding day out for hikers.\n\nWe rate it moderate to hard: the climb from the valley is long and steep, and you should be comfortable with 7 to 9 hours of walking in a day. We leave early from Dharamshala, drive to the trailhead in the Chamunda area, and plan to be back down before dark; groups who prefer a gentler pace can choose the overnight option with a camp or simple stay near the top, subject to availability and local rules. Distances, altitude and facilities at the top are approximate and vary between sources, and temple arrangements and trail access should be checked locally before you go; we confirm them before each departure. The shrine stays below the 3,000 m line in the January 2026 Kangra DDMA order on high treks, but weather-related closures can still apply.',
    itinerary: [
      { day: 1, title: 'Chamunda area to Adi Himani Chamunda and back', description: 'Early pick-up in Dharamshala (around 6 am) and drive to the trailhead near Chamunda Devi. Steep climb through forest and open slopes to the Adi Himani Chamunda shrine (approx. 4-5 hours), darshan and packed lunch at the top, then a careful descent (approx. 3-4 hours) and drive back to Dharamshala by evening. On the overnight option, we stay near the top and descend after sunrise the next morning.', distance: 'Approx. 14-18 km round trip', altitude: 'Approx. 2,700-2,800 m' },
    ],
    includes: ['Local guide familiar with the pilgrim trail', 'Return transfer Dharamshala to the trailhead', 'Packed lunch, snacks and tea', 'First aid kit'],
    excludes: ['Overnight camping or stay (quoted on request)', 'Temple offerings and donations', 'Insurance', 'Tips'],
    things_to_carry: ['Trekking shoes with good grip', 'Trekking poles for the steep descent', '2 litres of water', 'Warm layer and rain jacket', 'Headlamp (in case of a late finish)', 'Sun cap and sunscreen', 'Modest clothing for the shrine', 'Cash'],
    images: [],
    featured: false,
    faqs: [
      { question: 'How difficult is the Adi Himani Chamunda trek?', answer: 'Moderate to hard. The trail is not technical, but it climbs steeply for several hours from the valley, so a day trip means 7 to 9 hours of walking. Walking slowly and starting early make a big difference; the overnight option is gentler.' },
      { question: 'Is it the same as the Chamunda Devi temple?', answer: 'No. Chamunda Devi is the large temple beside the Baner river, about 15 km from Dharamshala on the Palampur road. Adi Himani Chamunda is the high shrine on the ridge above it, reached by a long uphill trek.' },
      { question: 'When should I avoid this trek?', answer: 'Avoid the monsoon (July and August) because of slippery trails and landslides, and winter months when snow can cover the upper section. Weather alerts can also lead to temporary closures, so we check conditions before every departure.' },
    ],
    status: 'published',
    meta_title: 'Adi Himani Chamunda Trek from Dharamshala: Guided Hike',
    meta_description: 'Guided trek to the Adi Himani Chamunda shrine above Chamunda Devi near Dharamshala: steep pilgrim trail, valley views, transfer and packed lunch included.',
  },
];
