/**
 * Generates supabase/migration-v9-directory-hotels.sql from the researched
 * directory listings in supabase/seed/directory/. Run with:
 *
 *   npx tsx scripts/generate-directory-sql.ts
 *
 * After the SQL has been run, Supabase is the source of truth: edit listings
 * in /admin/properties, not in these seed files. Re-running the SQL never
 * overwrites existing rows (ON CONFLICT (slug) DO NOTHING).
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { directoryHotels1 } from '../supabase/seed/directory/hotels-1';
import { directoryHotels2 } from '../supabase/seed/directory/hotels-2';
import { directoryMedia1 } from '../supabase/seed/directory/media-1';
import { directoryMedia2 } from '../supabase/seed/directory/media-2';
import { directoryMedia3 } from '../supabase/seed/directory/media-3';
import type { DirectoryHotel, DirectoryMedia } from '../supabase/seed/directory/types';

const AREA: Record<string, string> = {
  dharamshala: 'Dharamshala', 'mcleod-ganj': 'McLeod Ganj', bhagsu: 'Bhagsu', dharamkot: 'Dharamkot', naddi: 'Naddi',
};

const media: Record<string, DirectoryMedia> = { ...directoryMedia1, ...directoryMedia2, ...directoryMedia3 };

const q = (v: unknown) => (v === undefined || v === null || v === '' ? 'NULL' : "'" + String(v).replace(/'/g, "''") + "'");
const j = (v: unknown) => q(JSON.stringify(v ?? [])) + '::jsonb';
const b = (v: boolean | undefined) => (v === undefined ? 'NULL' : v ? 'TRUE' : 'FALSE');

function faqs(h: DirectoryHotel, m: DirectoryMedia | undefined) {
  const area = AREA[h.destination_slug];
  const out = [{ question: 'Where is ' + h.name + ' located?', answer: h.name + ' is in ' + h.locality + '.' + (h.nearby[0] ? ' Nearby: ' + h.nearby.slice(0, 2).join('; ') + '.' : '') }];
  if (m?.check_in_time) out.push({ question: 'What are the check-in and check-out times at ' + h.name + '?', answer: 'Check-in is from ' + m.check_in_time + (m.check_out_time ? ' and check-out is by ' + m.check_out_time : '') + '. Confirm early check-in or late check-out when you enquire.' });
  if (h.good_for.length) out.push({ question: 'Who is ' + h.name + ' best for?', answer: 'It suits ' + h.good_for.join(', ').toLowerCase() + '. See other stays in ' + area + ' if you want a different style or budget.' });
  out.push({ question: 'How do I check rates for ' + h.name + '?', answer: 'Send an enquiry or WhatsApp us with your dates and number of guests. We check availability and rates for you, or suggest a similar stay in ' + area + '.' });
  return out;
}

const rows = [...directoryHotels1, ...directoryHotels2].map((h) => {
  const m = media[h.slug];
  const images = (m?.images || []).filter((i) => i.url).map((i, n) => ({ url: i.url, alt: i.alt || h.name, category: i.category || 'other', is_primary: n === 0, sort_order: n }));
  const ownPhotos = images.length >= 3;
  const rooms = (m?.room_types || []).map((r) => ({
    name: r.name, description: r.description || '', bed_type: r.bed_type || '', max_occupancy: r.max_occupancy || null,
    base_price: 0, rate_plans: [], images: [], amenities: [], is_active: true,
  }));
  const notes = 'Directory listing added Oct 2026. Verified operating via: ' + h.sources.join(' , ')
    + (ownPhotos ? '' : '. No verified own photos yet -- page shows an area photo.');
  return '(' + [
    q(h.slug), q(h.name), q(h.type === 'cottage' ? 'homestay' : h.type), "'published'", "'directory'",
    q(h.description), q(h.short_description), q(h.destination_slug), q(h.locality), q(h.locality), q(AREA[h.destination_slug]), "'Himachal Pradesh'",
    j(Array.from(new Set([...h.amenities, ...(m?.amenities || [])]))), j(ownPhotos ? images : []), j(rooms), j(faqs(h, m)),
    q(m?.check_in_time), q(m?.check_out_time), q(m?.pet_policy), q(m?.smoking_policy), b(m?.couple_friendly),
    q(h.price_band), j(h.highlights), j(h.good_for), j(h.nearby), q(h.website), q(ownPhotos ? m?.photo_source : null),
    q(notes), '0', '0', '0', 'NOW()', "(SELECT id FROM profiles WHERE role = 'admin' ORDER BY created_at LIMIT 1)",
  ].join(', ') + ')';
});

const sql = `-- migration-v9: ${rows.length} directory hotel listings (generated by scripts/generate-directory-sql.ts)
-- Run AFTER migration-v8.sql. Safe to re-run: existing slugs are never overwritten,
-- so edits made in /admin/properties are kept.

INSERT INTO properties (
  slug, name, type, status, listing_type,
  description, short_description, destination_slug, address_line1, locality, city, state,
  amenities, images, rooms, faqs,
  check_in_time, check_out_time, pet_policy, smoking_policy, couple_friendly,
  price_band, highlights, good_for, nearby, website, photo_source,
  admin_notes, price_min, price_max, commission_pct, published_at, owner_id
) VALUES
${rows.join(',\n')}
ON CONFLICT (slug) DO NOTHING;
`;

const out = join(__dirname, '..', 'supabase', 'migration-v9-directory-hotels.sql');
writeFileSync(out, sql);
console.log('Wrote ' + rows.length + ' listings to ' + out);
